demo/config/routes.rb
Demo::Application.routes.draw do
  get "examples/files"

  get "examples/main"

  get "test/examples"

  get "math/examples"

  get "say/hello"

  get "say/goodbye"

end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

demo/app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  def main
  end
  def files
  	@files = Dir.glob("**/*")
  end
end

demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  end

  def goodbye
  end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/examples_helper.rb
module ExamplesHelper
end

demo/app/helpers/say_helper.rb
module SayHelper
end

demo/app/views/examples/files.html.erb
<h1>Files example</h1>
<p>
	<h2>Site file list: <br/></h2>
	<ul>
	<% for file in @files %>
		<li><i><%= file %></i> <br/></li>
	<% end %>]
	</ul>
</p>

demo/app/views/examples/main.html.erb
<h1>Some examples</h1>
<p>Addition: <%= 1+2 %></p>
<p>Concatenation: <%= "cow" + "boy" %></p>
<p>Time in one hour: <%= 1.hour.from_now %></p>

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo/app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>
	It was nice having you here.
</p>
<p>
	Say <%= link_to "Hello", say_hello_path %> again.
</p>

demo/app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<p>
	<%= link_to "Here", examples_main_path %> are some general examples
</p>
<p>
	And <%= link_to "here", examples_files_path %> are some file examples
</p>
<p>
	It is now <%= @time %>
</p>
<p>
	Time to say <%= link_to "Goodbye!", say_goodbye_path %>
</p>